#+TODO: TODO IN-PROGRESS WAITING DONE



* Project Scope 
This is the org file for the Project Individual Financial Management


** DONE TEST FOR AGENDA                                             :Christy:
   DEADLINE: <2020-03-19 Thu>
 - THIS IS TH NOTES


** DONE Research on OCR API                                         :Christy:
   DEADLINE: <2020-03-19 Thu>
 - which API could be used to extract data in PDF?
   - ocr.space: https://ocr.space/
     The ocr has been tested, the data could be extracted in unstructured-way.
   - package Tika 
     
 - could the data be directly gotten from the database from the banks?
     Use ocr is a better way for now.



** DONE Clean the extracted unstructured data  
   DEADLINE: <2020-03-25 Wed>
   After using the Tika package, the unstructured data can be obtained from Parsed['Content'],
which needs to be cleaned up.


** DONE Solve the amount issue
   DEADLINE: <2020-03-23 Mon>
  thousand separator can't be identified. 
  r"[-+]?\d{1,3}(?:\,\d{3})*,?\d+\b\.\d+" 


** TODO load the data into MSSQL database
   SCHEDULED: <2020-03-25 Wed>
   tested, not implemented yet.
